### ISSUE TITLE
Does this plugin work with Redactor II?

### ISSUE THREAD

**Issue by JWaldenback** [mildlygeeky/craft-redactorfontsize#1]
Hi!

I'm wondering if this plugin works with Redactor II (the newest Redactor)? From what I've understood they haven't made a font-size plugin for Redactor II, but in the credits it says "Thanks to Imperavi for writing the plugin".
 
Best regards!

**Comment by mildlygeeky** [comment]
Hello!

I don’t believe I have tested it with Redactor II. Happy to accept a pull
request if it needs refactoring to work with Redactor II.

**Comment by JWaldenback** [comment]
Thank you for your quick reply! I'm not a programmer (not yet at least ;-)) so I can't make a pull request.
